# Bu alıştırmada docker compose ile servis tanımlarken nasıl imaj oluşturacağımızı göreceğiz.
# Bu örnekte bir tane imajı önceden hazırlanmış imaj olarak kullanmayacağız. Onun yerine biz build edeceğiz.


version: '3.7'

services:
   mysqldb:
     image: ozgurozturknet/webdb
     environment:
      MYSQL_DATABASE: proje
      MYSQL_USER: projemaster
      MYSQL_PASSWORD: master1234
      MYSQL_ROOT_PASSWORD: master1234
     networks:
      - webnet

   websrv:
     build: . # Build komutuyla mevcut path içerisindeki dockerfile imaja dönüştürülür  ve kullanılır.
     depends_on:
       - mysqldb
     ports:
       - "80:80"
     restart: always
     networks:
       - webnet
     environment:
       DB_SERVER: mysqldb
       DB_USERNAME: projemaster
       DB_PASS: master1234
       DB_NAME: proje
networks:
  webnet:
    driver: bridge


# docker compose up -d komutu ile docker-compose.yml file çalıştırılır.
# docker compose images ile servislerin hangi imajdan yaratıldığı görülür.
# docker ps ile servise ait container'lar görülür.

# Eğer compose ile servis oluşturduktan sonra değişiklik yapılırsa docker compose up komutu imajı tekrar oluşturmaz. Bu komut öncesinde
# docker compose build çalıştırılmalı ve sonrasında docker compose up komutu çalıştırılmalıdır.
# docker compose build imajı tekrar olusturur.