# Bu alıştırma bir web container'ı ve bir database'den oluşan bir servisin tanımlanma örneği.

version: "3.7"

#@1.Kısım
# İlk olarak servisimi oluşturuyorum.
# Servisi oluşturduktan sonra altındaki container'ları tanımlıyorum ve isim veriyorum. Burada ilk container ismi mysqldb
# Her kırılım altında işlem yaparken, yaml'da hiyerarşik bir yapı olduğu için taba basıyorum.
# Bu şu demek; Ben bir servis oluşturdum. Onun altında mysqldb isimli bir container var. Onun altına image vs. diyerek gidiyor.
# Aslında servisin altında container'ı oluşturduktan sonra onun tanımlarını yapıyorum.

#1. Kısım
services: 
  mysqldb:
    image: ozgurozturknet/webdb
    environment:
      MYSQL_DATABASE: proje
      MYSQL_USER: projemaster
      MYSQL_PASSWORD: master1234
      MYSQL_ROOT_PASSWORD: master1234
    networks:
      - webnet

  websrv: #Bir servisin altında birden fazla container olabilir demiştik. Şimdi ikincisini tanımlayacağız.
    depends_on: # mysqldb servisine bağımlılığını ifade ediyoruz. Eğer mysqldb container'ı up olamıyorsa websrv container'ının da up olması mantıklı değil.
      - mysqldb
    image: ozgurozturknet/webkayit # Container'ın kullandığı imaj.
    ports: # Port publish ediyoruz.
      - "80:80"
    restart: always # Eğer container'da bir sorun çıkarsa restart etmesini söylüyoruz.
    networks: # webnet network'üne bağlıyoruz.
      - webnet
    environment: # mysqldb container'ındaki database bağlanabilmesi için environment variable tanımlarını yapıyoruz.
      DB_SERVER: mysqldb
      DB_USERNAME: projemaster
      DB_PASS: master1234
      DB_NAME: proje

networks: # Network create ediyoruz.
  webnet: # Network ismini yazıyoruz.
    driver: bridge # Network create ederken kullanacağımız driver'ı belirtiyoruz.




